### ISSUE TITLE
documentation error?

### ISSUE THREAD

**Issue by apb2006** [Corbas/xproc-tools#2]
https://github.com/Corbas/xproc-tools/blob/master/README.md#processed-items
````
<manifest xmlns="http://www.corbas.co.uk/ns/transforms/data">
  <processed-item stylesheet="mapper.xsl">
    <item href="data01.xml"/>
  </processed-item>
  <item href="data-02.xml"/>
</manifest>
````
The result of loading this manifest would be a sequence of two documents, data-01.xml and the output of processing data-02.xml with mapper.xsl. Only the XSLT's primary output is used, any secondaries 

I think this should be:
The result of loading this manifest would be a sequence of two documents, the output of processing `data-01.xml` with `mapper.xsl`.  and `data-02.xml`  Only the XSLT's primary output is used, any secondaries

**Comment by nicg-corbas** [comment]
Yeah, you're right. Fixed and commited
